### ISSUE TITLE
Como contribuir a este proyecto? 

### ISSUE THREAD

**Issue by juanbono** [UTN-FRD/construccion-compilador#1]
Hola! 
Que tal?
Hace unas semanas que vengo aprendiendo Rust y en paralelo me encontre con este proyecto, por lo que me gustaria ayudar en lo que se pueda.
Hay alguna forma en la que pueda contribuir?

**Comment by franleplant** [comment]
Hola Juan! Definitivamente que si. Pero necesito un poco de tiempo para
setear la infra, lo cual voy a estar haciendo en la prox semana. El código
esta en mi github personal, se llama Lisp2018, tambien tengo planeado de
alguna manera unificar ambos repos.
